### ISSUE TITLE
Oceanographer crashing while leveling up 

### ISSUE THREAD

**Issue by Robbielewis** [samedifferent/morevillagers#31]
## Bug Report

[ All of the lines between [ ] (square brackets) should be deleted before posting. ]

### the issue I am encountering is when I level up the ocean villager to the third level it completely crashes my game. 

I was levelling up my villagers and when I started levelling the ocean one my game would become incredibly laggy and then crash. I tried three times to level the villager up but it didn't work. 

Simply just level one up and you should encounter the issue. 

Spawn in a villager and give it the correct workbench, once it takes the job level it up to the third stage. 

I'm on the latest version of the mod

**Comment by samedifferent** [comment]
Please attach your log file

**Comment by racoon23** [comment]
Hi, I'm having the same kind of issue using this modpack : [Better Minecraft [Fabric]](https://www.curseforge.com/minecraft/modpacks/better-minecraft-fabric). 
I have not tried the oceanographer but the netherian. The issue happens when completing a trade to level them to level 3 then exiting the trade screen.

The server does not crash - it simply stops responding. Clients are disconnected with a message saying "Timed out". Issuing the "stop" command in the server console won't work, you have to kill the process. This makes you lose your world progress for the last 10 or 15 minutes.

Here's my [server log.](https://github.com/samedifferent/morevillagers/files/7239661/2021-09-23-2.log)

I have not been able to replicate the issue while in single player mode, it only seems to happen using a dedicated server. In my instance I have been using the [server pack provided by the modpack](https://www.curseforge.com/minecraft/modpacks/better-minecraft-fabric/files/3462517)

**Comment by PhoenixVX** [comment]
The log doesn't provide much info before it stops responding. I'll take a look at it with some of the last few mods mentioned in the log file, but it would greatly help us if you could identify which mods have it occur.

**Comment by samedifferent** [comment]
Issue is with another mod.
