### ISSUE TITLE
[Bug]: Compatibility issue with waystones

### ISSUE THREAD

**Issue by KMFrench1** [samedifferent/morevillagers#46]
### Mod Version

3.1.1

### Mod Loader

Fabric

### Mod Loader Version

0.12.12

### What happened?

More village structures cause waystones (https://www.curseforge.com/minecraft/mc-mods/fabric-waystones) to not spawn, If i disable all your structure in the configs then waystones start spawning in villages again.

### latest.log

https://gist.github.com/KMFrench1/c2107b0f696f53652ac44afa76ed1b6b

**Comment by PhoenixVX** [comment]
Forgive me for not responding in a timely manner. I've been quite busy with school and other business.
Does this issue occur with only MoreVillagers (Fabric) and Fabric-Waystones?

Right now, your log is nearly unreadable due to so many cascading issues, which may be messing with spawn weights.
Otherwise, the spawn weight for MoreVillagers' houses may be too high to spawn the waystones.

I will be giving this issue a month from today, before it is closed. Please respond if you wish to see this fixed/rerouted.

**Comment by Solbright** [comment]
This also occurs with the original [Waystones (Fabric Edition)](https://www.curseforge.com/minecraft/mc-mods/waystones-fabric) mod. Even when set to force spawn in villages, Waystones do not appear. The added structures and jobs in more villagers are great, and I'd like to see the two mods co-exist.

**Comment by PhoenixVX** [comment]
😮‍💨 Completely forgot about this issue. Can you attempt this with a clean log (I.E. bare minimum mods)?

**Comment by Solbright** [comment]
Created a new install with only More Villagers, Waystones, Village Spawn Point (To make testing faster) and mod menu (to change the Waystones settings and force spawn in villages). So far three worlds, three villages, and no Waystones.

**Comment by SirUmnei** [comment]
This seems to happen with the Forge version as well. However, the Waystones DO spawn, but very far away from the village or at the very edge.

**Comment by samedifferent** [comment]
It turns out I was duplicating the pool entries when adding the more villagers houses to the vanilla village pools. This should be fixed now in the latest 1.18.2 and 1.19 builds.
